const groups = {
  AMAZONIA: "AMAZÔNIA",
  ANDIROBA: "ANDIROBA",
  ANGELIM: "ANGELIM",
  "ARARA.AZUL": "ARARA-AZUL",
  ARAUCARIA: "ARAUCÁRIA",
  ARIRANHA: "ARIRANHA",
  BRAUNA: "BRAÚNA",
  BROMELIA: "BROMÉLIA",
  CAATINGA: "CAATINGA",
  CAIXETA: "CAIXETA",
  CAMPOS: "CAMPOS",
  CASTANHEIRA: "CASTANHEIRA",
  CEDRO: "CEDRO",
  CEREJEIRA: "CEREJEIRA",
  CERRADO: "CERRADO",
  CHAUA: "CHAUÁ",
  DESERTO: "DESERTO",
  FLORESTAS: "FLORESTAS",
  GARAPEIRA: "GARAPEIRA",
  "GATO.MARACAJA": "GATO-MARACAJÁ",
  "GAVIAO.REAL": "GAVIÃO-REAL",
  IMBUIA: "IMBUIA",
  JACARANDA: "JACARANDÁ",
  JACUTINGA: "JACUTINGA",
  JATOBA: "JATOBÁ",
  JEQUITIBA: "JEQUITIBÁ",
  "LOBO.GUARA": "LOBO-GUARÁ",
  "MATA.ATLANTICA": "MATA ATLÂNTICA",
  "MICO.LEAO.DOURADO": "MICO-LEÃO-DOURADO",
  MOGNO: "MOGNO",
  MURIQUI: "MURIQUI",
  "ONCA.PINTADA": "ONÇA-PINTADA",
  PAMPAS: "PAMPAS",
  PANTANAL: "PANTANAL",
  "PAU.BRASIL": "PAU-BRASIL",
  SAGUI: "SAGUI",
  SAVANA: "SAVANA",
  TAIGA: "TAIGA",
  "TAMANDUA.BANDEIRA": "TAMANDUÁ-BANDEIRA",
  "TARTARUGA.GIGANTE": "TARTARUGA-GIGANTE",
  "TATU.BOLA": "TATU-BOLA",
  TUCUXI: "TUCUXI",
  TUNDRA: "TUNDRA",
  UACARI: "UACARI",
};

const validateGroupName = (groupName) => {
  for (group in groups) {
    if (new RegExp(group).test(groupName)) return groups[group];
  }
  throw new Error(`Invalid group name: ${groupName}`);
};

module.exports = validateGroupName;
